In [43]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import Imputer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import StandardScaler

In [23]:
dataset = pd.read_csv("C:/Users/Ananta Arora/Documents/ML2/Data Preprocessing/Data_Prerocessing/Data.csv")


In [24]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

# Matrix Of Features 
X = dataset.iloc[:,:-1].values

* Note - first : denotes all the lines (columns), :-1 all the lines (columns) except the last one
* Note - Y = dataset.iloc[:, 3].values #index for last column is 3

In [15]:
X = dataset.iloc[:,:-1].values
Y = dataset.iloc[:, 3].values

In [16]:
dataset.head()


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [17]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [18]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [19]:
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

** As you can see Age is missing in the seventh row. Salary data is missing in the 5th row **

### How to deal with missing data ?
 * If we delete those columns then it is a problem because we will miss the crucial information so
 we will take mean of the all the data in that particular column

* why  imputer ?
> To check the parameters of any function or class.. We can also check the documentation on the website

* Note - if axis -0 then impute along columns
* Note - if axis - 1 then impute along rows 

In [28]:
imputer = Imputer(missing_values = "NaN", strategy = "mean", axis = 0)

imputer = imputer.fit(X[:, 1:3]) #3 because upper bound is excluded

#replace missing data

X[:, 1:3] = imputer.transform(X[:, 1:3])

In [29]:
print (X)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## How to handle categorical Data ?

* We have two categorical column Country and Purchased

 ** Reason? ** 

>Simply, bc they contain categories

>Country contains 3 categories : France, Spain and Germany

>Purchased contains 2 categories : Yes, No

* Problem - since now france,germany and spain are ordered as 1,2,3 but if 2 comes before 1 then there could be a problem because the machine would misinterpret that germany is greater than spain which is not true and making no sense so we will use dummy variables -which doesnt follow order 

In [32]:
#creating object

labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0]) #Still a problem : refer video since, ML algo will take it as higher value country is special or something like that

#To prevent this we will use dummy encoding
onehotencoder = OneHotEncoder(categorical_features = [0])

X = onehotencoder.fit_transform(X).toarray()

In [33]:
print(X)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 2.70000000e+01
  4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 5.00000000e+01
  8.30000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  6.70000000e+04]]


In [34]:
#Now for Purchased column

labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(Y)


In [36]:
print(Y) 
# 0 - NO and 1- YES 

[0 1 0 0 1 1 0 1 0 1]


## Splitting the Dataset into Training Set and Testing  Set :
* Need 
> Machine is going to learn something on the datasets. Then we need it to test it on some different test sets. We will train it using some data then we will test it with some data which won't be much different than the training data.

In [38]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0) #testSize is in percentage

In [41]:
X_test

array([[0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04]])

### Feature Scaling
* Why we need this?
> To decrease the dominance of different scale of data.

**  Standardisation ** 
* $Xstand = \frac{X - mean(X)}{standard deviation (X)}$

** Normalisation **

 * $Xnorm = \frac{X - min(X)}{max(X) - min(X)}$

In [44]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test) #don't need to fit bc already fitted the training sets

# Do we need to fit or transform Dummy variables?
## We can scale those dummy variables..

In [46]:
print(X_train)

print("\n Now the X test \n")

print(X_test)

[[-1.          2.64575131 -0.77459667  0.26306757  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.25350148  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.97539832 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.05261351 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.64058505  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.0813118  -0.16751412]
 [ 1.         -0.37796447 -0.77459667  0.95182631  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.59788085 -0.48214934]]

 Now the X test 

[[-1.          2.64575131 -0.77459667 -1.45882927 -0.90166297]
 [-1.          2.64575131 -0.77459667  1.98496442  2.13981082]]


** Do we need to apply feature scaling to dependent variable Y? ** 
 * No, because we have only 2 categorical value